"""empty message

Revision ID: 13fe7ecd617b
Revises: 5880b3b936fa
Create Date: 2020-10-27 14:48:18.627291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fe7ecd617b'
down_revision = '5880b3b936fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('m_sales', sa.Integer(), nullable=True))
    op.add_column('goods', sa.Column('w_sales', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'w_sales')
    op.drop_column('goods', 'm_sales')
    # ### end Alembic commands ###
