"""empty message

Revision ID: 1a9da7723eb7
Revises: 13fe7ecd617b
Create Date: 2020-10-27 15:10:57.178036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9da7723eb7'
down_revision = '13fe7ecd617b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('buying_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'buying_price')
    # ### end Alembic commands ###
