"""empty message

Revision ID: 5880b3b936fa
Revises: a040ea18f992
Create Date: 2020-10-27 11:17:47.159874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5880b3b936fa'
down_revision = 'a040ea18f992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('d_sales', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'd_sales')
    # ### end Alembic commands ###
