"""empty message

Revision ID: c00c6c3c2270
Revises: 
Create Date: 2020-10-26 18:57:56.982491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00c6c3c2270'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('colour', sa.String(length=128), nullable=True),
    sa.Column('launch_date', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
